WORDS = [
    "maktab", "orzu", "baxt", "sevgi", "ishonch",
    "hayot", "ilm", "dostlik", "osmon", "quyosh",
    "yulduz", "oy", "yer", "vatan", "inson",
    "daryo", "tog", "gul", "bog", "shamol",
    "yomgir", "qor", "bahor", "yoz", "kuz",
    "qish", "ota", "ona", "aka", "uka",
    "opa", "singil", "oila", "uy", "xona",

    "eshik", "deraza", "stol", "kursi", "sumka",
    "ruchka", "chiroq", "devor", "pol", "shift",
    "non", "suv", "osh", "choy", "qahva",
    "olma", "anor", "uzum", "shaftoli", "nok",
    "sabzi", "piyoz", "kartoshka", "bodring", "pomidor",
    "baliq", "qush", "it", "mushuk", "ot",
    "sigir", "quyon", "ari", "kapalak", "boyqush",

    "tezlik", "kuch", "zamon", "vaqt", "kun",
    "hafta", "oylik", "yillik", "kelajak", "otmish",
    "hozir", "xotira", "fikr", "maqsad", "goya",

    "mehnat", "zafar", "galaba", "harakat", "natija",
    "sabr", "umid", "quvonch", "tabassum", "mehr",
    "oqibat", "sadoqat", "hurmat", "adolat", "haqiqat"
]

MESSAGES = [
    "sizga aytadigan gaplarim juda ko'p... ❤️ — Shohjahondan",
    "Siz bilan bog‘liq har bir xotira men uchun qadrli... ❤️ — Shohjahondan",
    "Ba'zan inson nimanidir aytishga jur'at topolmaydi... ❤️ — Shohjahondan",
    "Chunki ba'zi hislar juda samimiy bo‘ladi... ❤️ — Shohjahondan",
    "Sizni taniganimdan beri hayotim boshqacharoq bo‘lib qoldi... ❤️ — Shohjahondan",
    "Oddiy suhbatlarimiz ham men uchun qadrli edi... ❤️ — Shohjahondan",
    "Har safar siz bilan gaplashganda yuzimda tabassum paydo bo‘lardi... ❤️ — Shohjahondan",
    "Balki siz buni sezmagandirsiz... ❤️ — Shohjahondan",
    "Lekin qalbim sizni allaqachon boshqalardan ajratib qo‘ygandi... ❤️ — Shohjahondan",
    "Shu paytgacha aytolmagan bir gapim bor edi... ❤️ — Shohjahondan",
    "Bu gapni aytish uchun ko‘p vaqt kutdim... ❤️ — Shohjahondan",
    "Chunki siz men uchun oddiy inson emassiz... ❤️ — Shohjahondan",
    "Siz qalbimda alohida o‘rin egallagansiz... ❤️ — Shohjahondan",
    "Va bu o‘rinni hech kim bosa olmaydi... ❤️ — Shohjahondan",
    "Bugun sizga bir sirimni aytmoqchiman... ❤️ — Shohjahondan",
    "Men siz haqingizda juda ko‘p o‘ylayman... ❤️ — Shohjahondan",
    "Va bu o‘ylar har doim yuragimga iliqlik beradi... ❤️ — Shohjahondan",
    "Chunki siz menga juda yoqasiz... ❤️ — Shohjahondan",
    "Rostini aytsam... ❤️ — Shohjahondan",
    "Men sizni sevib qolganman... ❤️ — Shohjahondan",
    "Bu o‘yinning asl maqsadi ham shu gapni aytish edi... ❤️ — Shohjahondan",
    "Siz javobingiz qanday bo‘lishidan qat'i nazar qadrli insonsiz... ❤️ — Shohjahondan",
    "Qalbimdagi hislarni bilishingizni istadim xolos... ❤️ — Shohjahondan",
    "Va oxirgi gap... ❤️ — Shohjahondan",
    "Men sizni sevaman. ❤️🌹 — Shohjahondan",
    "Siz bu o‘yinda oddiy o‘yinchi emassiz... ❤️ — Shohjahondan",
    "Har bir bosqich sizni bir narsaga yaqinlashtiryapti... ❤️ — Shohjahondan",
    "Ba’zi so‘zlar oddiy emas, ular ma’no beradi... ❤️ — Shohjahondan",
    "Sizning har bir javobingiz tarix yozmoqda... ❤️ — Shohjahondan",
    "Bu faqat o‘yin emas... bu hislar yo‘li... ❤️ — Shohjahondan",
    "Sog‘indim... ❤️ — Shohjahondan",
    "Sizni juda yaxshi ko‘raman... ❤️ — Shohjahondan",
    "Siz menga keraksiz... ❤️ — Shohjahondan",
    "Siz mening eng yaqinimsiz... ❤️ — Shohjahondan",
    "Mening oxirgi muhabbatim sizsiz... ❤️ — Shohjahondan",
    "Ba'zi insonlar qalbda iz qoldiradi... ❤️ — Shohjahondan",
    "Siz bu yo‘lda oddiy o‘yin o‘ynamayapsiz... ❤️ — Shohjahondan",
    "So‘zlar tugashi mumkin, lekin hislar yo‘q... ❤️ — Shohjahondan",
    "Ba'zan bir inson butun dunyongizga aylanadi... ❤️ — Shohjahondan",
    "Sizni uchratganim tasodif emasdek tuyuladi... ❤️ — Shohjahondan",
    "Qalbimdagi eng chiroyli sahifa siz bilan bog‘liq... ❤️ — Shohjahondan",
    "Har bir tabassumingiz kunimni yoritadi... ❤️ — Shohjahondan",
    "Sizni o‘ylamasdan o‘tgan kunim yo‘q... ❤️ — Shohjahondan",
    "Ba'zi insonlar unutiladi, ba'zilari esa yurakda qoladi... ❤️ — Shohjahondan",
    "Har bir kunimda siz haqingizdagi bir o‘y yashaydi... ❤️ — Shohjahondan",
    "Siz mening eng go‘zal xotiram bo‘lib qoldingiz... ❤️ — Shohjahondan",
    "Masofalar uzoq bo‘lsa ham, qalb yaqin bo‘lishi mumkin... ❤️ — Shohjahondan",
    "Ko‘zlarim sizni izlasa, yuragim allaqachon topgan... ❤️ — Shohjahondan",
    "Har bir hikoyaning eng go‘zal qismi sevgi bilan yoziladi... ❤️ — Shohjahondan",
    "Siz bilan oddiy lahzalar ham qadrli bo‘lib qoladi... ❤️ — Shohjahondan",
    "Mening eng sokin baxtim siz haqingizdagi o‘ylardir... ❤️ — Shohjahondan",
    "Ba'zan bir inson minglab so‘zlardan qadrliroq bo‘ladi... ❤️ — Shohjahondan",
    "Yuragimdagi eng chiroyli tilak siz bilan bog‘liq... ❤️ — Shohjahondan",
    "Siz bor joyda qalbim o‘zini uyidagidek his qiladi... ❤️ — Shohjahondan",
    "Muhabbat ba'zan bir insonning ismida yashirinadi... ❤️ — Shohjahondan",
    "Sizni eslash uchun sabab kerak emas... ❤️ — Shohjahondan",
    "Eng go‘zal hislar ko‘pincha so‘zsiz tushuniladi... ❤️ — Shohjahondan",
    "Qalbim sizni tanlaganiga afsus qilmaganman... ❤️ — Shohjahondan",
    "Ba'zi insonlar taqdir tomonidan yuborilgandek tuyuladi... ❤️ — Shohjahondan",
    "Muhabbatning ma'nosini siz orqali tushundim... ❤️ — Shohjahondan",
    "Eng go‘zal orzularimning markazida siz borsiz... ❤️ — Shohjahondan",
    "Siz bilan oddiy lahzalar ham unutilmas bo‘lib qoladi... ❤️ — Shohjahondan",
    "Ba'zi hislarni so‘z bilan tushuntirib bo‘lmaydi... ❤️ — Shohjahondan",
    "Agar yuragim gapira olsa, faqat siz haqingizda so‘zlardi... ❤️ — Shohjahondan"
    "Har safar tabassumingizni eslasam, yuzimda ham tabassum paydo bo‘ladi... ❤️ — Shohjahondan",
    "Men siz haqingizda juda ko‘p o‘ylayman... ❤️ — Shohjahondan",
    "Men sizni sevib qolganman... ❤️ — Shohjahondan",
    "Siz mening eng go‘zal tasodifimsiz... ❤️ — Shohjahondan",

]